### ISSUE TITLE
OneStepLeverage.sol : `manageLeveragedPosition()` allows the leveraging even if the collateral is not enabled

### ISSUE THREAD

**Issue by aktech297** [raft-fi/contracts#371] opened 2023-05-18 17:41 UTC
`Severity:` Medium

`Summary:`

The collateral which is disabled by owner can be used to leverage under certain condition which can bypass the `isEnabled` check.

`Issue details:`

`OneStepLeverage.sol` has the `manageLeveragedPosition` function, which takes the following input parameters and leverage the position
        uint256 debtChange,
        bool isDebtIncrease,
        uint256 principalCollateralChange,
        bool principalCollateralIncrease,
        bytes calldata ammData,
        uint256 minReturnOrAmountToSell,
        uint256 maxFeePercentage

function  - manageLeveragedPosition calls the [https://github.com/raft-fi/contracts/blob/03bbbe70a158484cdd63713c51ca7444f77032bf/contracts/OneStepLeverage.sol#LL65C14-L65C14](url) after transferring the collateral from user to the contract address. 

Incase the debt is not gonna increased, `_manageLeveragedPosition` function has the following logic,

        if (!isDebtIncrease) {
            uint256 positionDebt = IPositionManager(positionManager).raftDebtToken().balanceOf(msg.sender);
            if (debtChange == type(uint256).max) {
                debtChange = positionDebt;
            }
            fullRepayment = (debtChange == positionDebt);

            (IERC20Indexable raftCollateralToken,) = ----------------------------------->>> audit find where the isEnabled is not used.
                IPositionManager(positionManager).raftCollateralTokens(collateralToken); 
            actualCollateralChange =
                fullRepayment ? raftCollateralToken.balanceOf(msg.sender) : principalCollateralChange;
        } else {

In above logic, `raftCollateralToken` is get from `positionManager` and the balance from `raftCollateralToken` for the msg.sender if used for fullRepayment secnario.

For some reason, if the raftCollateralToken is disabled due the nature of malicioud nature. This maliciouos colllateral contract would be used to repay the debt and witdraw collateral.

The owner can call the [https://github.com/raft-fi/contracts/blob/03bbbe70a158484cdd63713c51ca7444f77032bf/contracts/PositionManager.sol#L345](url) function and disable it.

`Attack secnario:`

User deosit collateral and interact with contract.

After some time, owner finds that the collateral is malicioud or tunrs into non-stnadard and go for disabling it by by calling the [https://github.com/raft-fi/contracts/blob/03bbbe70a158484cdd63713c51ca7444f77032bf/contracts/PositionManager.sol#L345](url)

The reason could be malicious nature or allowing the collateral to interact further could cause any kind of issue.

Note : the check in `managePosition` function is not sufficient to check for isEnabled since it has logic to pass. This can be easily bypassd.

managePosition has below logic to check for isEnabled. The conditon `isDebtIncrease && debtChange > 0)` can be used to bypass the `onlyEnabledCollateralTokenWhen` check.

        onlyEnabledCollateralTokenWhen(collateralToken, isDebtIncrease && debtChange > 0)

`Remediation`

        if (!isDebtIncrease) {
            uint256 positionDebt = IPositionManager(positionManager).raftDebtToken().balanceOf(msg.sender);
            if (debtChange == type(uint256).max) {
                debtChange = positionDebt;
            }
            fullRepayment = (debtChange == positionDebt);

            (IERC20Indexable raftCollateralToken, bool isEnabled) = -------------------------------------->> @@@ audit updated
                IPositionManager(positionManager).raftCollateralTokens(collateralToken);

           require(isEnabled); -------------------------------------------------------------------------------->>audit updated
            actualCollateralChange =
                fullRepayment ? raftCollateralToken.balanceOf(msg.sender) : principalCollateralChange;
        } else {

**Comment by mijovic** [comment] 2023-05-18 19:57
User should be able to decrease debt by design when collateral is disabled. One of the actions that we want in case of disabled collateral is user closing the position and getting his collateral back.
This is not an issue if it is done via delegates as well.

**Closed by mijovic** 2023-05-18 19:57 UTC
